#%RAML 0.8
title: Sample API
version: 1.0
baseUri: http://localhost:8080/api

/get:
 get:
  description: sample
  responses: 
   200:
    body: 
     text/plain:
      example: This is get call, MULE flow from RAML
      
/show:
 get: 
  description: sample
  responses: 
   200:
    body: 
     text/plain:
      example: This is get call and name show , mule flow from RAML
      
  